{{- if .Values.appid_credentials -}}
apiVersion: v1
data:
#  binding: {{ .Files.Get (printf "%s" .Values.appid_credentials)  | b64enc | quote }}
  binding: {{ .Values.appid_credentials | toJson | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Release.Name }}-appid
  type: Opaque
{{- end -}}
