# Default values for simpleapp.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
image:
  repository: de.icr.io/renemeyer/simpleapp
  tag: latest
  pullPolicy: Always
# your IBM Cloud MongoDB Connection String
mongodb_url: "mongodb://ibm_cloud_XXX:XXX@HOST1:30212,HOST2:30212/ibmclouddb?authSource=admin&replicaSet=replset"
# your IBM Cloud base64 cert
certificate_base64: "LS....="
